# Integration scSHM data with WILLOW

In [1]:
#Load packages
options(warn=-1)
library("IRdisplay")
library(tidyverse)
library(ggplot2)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
df_summary <- read.csv("output/df_summary.csv")

In [3]:
print("Number of scSHM cells")
df_summary %>% pull(cell) %>% unique() %>% length()

# scSHM cells list
scSHM_cells <-df_summary %>% pull(cell) %>% unique()

[1] "Number of scSHM cells"

[1] 71

In [19]:
clone_id <- readRDS("~/repositories/FL_10X_2/250_Clonotypes.freeze02/outs/clonesB_20210823.rds") %>% mutate(cell = gsub(".{2}$", "", barcode)) %>%
            filter(cell %in% scSHM_cells)

In [5]:
#### is_cell : True or False value indicating whether the barcode was called as a cell.

#In addition to the three requirements listed above, Cell Ranger v3.1 (and later) has a filter to account for noise introduced by plasma cells and B cells 
#containing large amounts of RNA (as documented in the Cell Ranger 3.1 release notes). This 1) tightens the is_cell filter for low-frequency clones that 
#share a chain with a higher-frequency or large clone, and 2) shrinks high-frequency clones to remove noise from mRNA leakage caused by sample processing 
#(e.g. not due to biological clonal expansion).

#https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/algorithms/cell-calling

#Compute the N50 value of the number of read pairs per UMI, across all barcodes. For a given barcode, if the maximum read pair count across filtered UMIs 
#is less than 3% of this N50, do not call the barcode a cell. This provides some protection against transcripts arising from index hopping on an Illumina 
#flowcell, and from other forms of cross-library contamination.

#maybe there are not so much reads for the UMI by problems in the aligment??? for that reason is considered as FALSE

In [6]:
str(clone_id)

Classes ‘data.table’ and 'data.frame':	165 obs. of  55 variables:
 $ source                : chr  "K1B" "K1B" "K1B" "K1B" ...
 $ cell                  : chr  "AACTCAGCATTCGACA" "AACTCAGCATTCGACA" "AACTCAGCATTCGACA" "AACTCTTGTGCAACTT" ...
 $ Sequence ID           : chr  "AACTCAGCATTCGACA-1_contig_1" "AACTCAGCATTCGACA-1_contig_2" "AACTCAGCATTCGACA-1_contig_3" "AACTCTTGTGCAACTT-1_contig_1" ...
 $ V-DOMAIN Functionality: chr  "productive" "productive" "productive" "productive" ...
 $ V-GENE and allele     : chr  "IGKV1-17*01 F" "IGKV1-17*01 F" "IGHV3-30*03 F, or IGHV3-30*18 F or IGHV3-30-5*01 F" "IGKV3-20*01 F" ...
 $ J-GENE and allele     : chr  "IGKJ4*01 F" "IGKJ4*01 F" "IGHJ6*02 F" "IGKJ2*01 F" ...
 $ D-GENE and allele     : chr  NA NA "IGHD3-10*01 F" NA ...
 $ V-REGION              : chr  "gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccttcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcag"| __truncated__ "gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcag"| __truncated__ "caggagcaactggtggagtctgggggaggcgtgatccagcctgggaggtccctgagactctcctgtgcagcctctcgatttatcttcagtaactttggcatgcactgggtc"| __truncated__ "gaagttgtattgacgcagtctccaggcaccctgtctctgtctccagggcaaagagccaccctctcctgcagggccagtcagagtattagtagcagctacttagcctggtac"| __truncated__ ...
 $ FR3-IMGT              : chr  "agtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttacttctgt" "agtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgt" "tactatggcgacttcgtgaagggccgattcaccatctccagagacaattccaagaacacggtgtatttgcaaatgaacagcctgagacctgatgacacggctgtatatttctgt" "agcaaggccactggcatcccagacaggttcactggcaacgggtctgggacagacttcactctcaacatcggcagactggagactgaagattttgcagtgtattactgt" ...
 $ FR4-IMGT              : chr  "ttcggcggagggaccaaggtggagatcaaac" "ttcggcggagggaccaaggtggagatcaaac" "tggggccaagggaccacggtcaccgtctcgtca" "tttggccaggggaccaaggtggagatcaaag" ...
 $ JUNCTION              : chr  "tgtctacagcataatacttacccactcgctttc" "tgtctacagcataatacttacccactcgctttc" "tgtgcgagggggcgtggggcgttcgcagtgatgcgaggcggcgactacaacggtatggacgtctgg" "tgtcaacagtatggtaggtctccgtacactttt" ...
 $ Vregion3Prime         : chr  "tgtctacagcataatacttaccc" "tgtctacagcataatacttaccc" "tgtgcgag" "tgtcaacagtatggtaggtctcc" ...
 $ FR1-IMGT start        : num  99 99 138 94 138 101 138 94 138 100 ...
 $ FR3-IMGT end          : num  362 362 425 360 425 364 425 357 425 363 ...
 $ FR4-IMGT start        : num  390 390 486 388 471 392 486 385 486 391 ...
 $ J-REGION              : chr  "ctcgctttcggcggagggaccaaggtggagatcaaac" "ctcgctttcggcggagggaccaaggtggagatcaaac" "actacaacggtatggacgtctggggccaagggaccacggtcaccgtctcgtca" "gtacacttttggccaggggaccaaggtggagatcaaag" ...
 $ CDR3-IMGT             : chr  "ctacagcataatacttacccactcgct" "ctacagcataatacttacccactcgct" "gcgagggggcgtggggcgttcgcagtgatgcgaggcggcgactacaacggtatggacgtc" "caacagtatggtaggtctccgtacact" ...
 $ FR4-IMGT end          : num  420 420 518 418 504 422 518 415 518 421 ...
 $ seq                   : chr  "gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccttcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcag"| __truncated__ "gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcag"| __truncated__ "caggagcaactggtggagtctgggggaggcgtgatccagcctgggaggtccctgagactctcctgtgcagcctctcgatttatcttcagtaactttggcatgcactgggtc"| __truncated__ "gaagttgtattgacgcagtctccaggcaccctgtctctgtctccagggcaaagagccaccctctcctgcagggccagtcagagtattagtagcagctacttagcctggtac"| __truncated__ ...
 $ gene                  : chr  "K" "K" "H" "K" ...
 $ genes                 : chr  NA NA NA "HK" ...
 $ contigCount           : int  1 1 1 1 1 1 1 1 1 1 ...
 $ barcode               : chr  "AACTCAGCATTCGACA-1" "AACTCAGCATTCGACA-1" "AACTCAGCATTCGACA-1" "AACTCTTGTGCAACTT-1" ...
 $ is_cell               : logi  FALSE FALSE FALSE TRUE TRUE TRUE ...
 $ high_confidence       : logi  FALSE FALSE FALSE TRUE TRUE TRUE ...
 $ length                : num  556 556 590 554 575 558 590 551 590 557 ...
 $ chain                 : chr  "IGK" "IGK" "IGH" "IGK" ...
 $ v_gene                : chr  "IGKV1-17" "IGKV1-17" "IGHV3-30" "IGKV3-20" ...
 $ d_gene                : chr  "None" "None" "None" "None" ...
 $ j_gene                : chr  "IGKJ4" "IGKJ4" "IGHJ6" "IGKJ2" ...
 $ c_gene                : chr  "IGKC" "IGKC" "IGHM" "IGKC" ...
 $ full_length           : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ productive            : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ cdr3                  : chr  "CLQHNTYPLAF" "CLQHNTYPLAF" "CARGRGAFAVMRGGDYNGMDVW" "CQQYGRSPYTF" ...
 $ reads                 : num  3644 3140 1580 7664 718 ...
 $ umis                  : num  17 15 9 43 3 49 8 29 10 19 ...
 $ V-REGION identity %   : num  97.1 97.8 92.7 94.3 92 ...
 $ seqRaw                : chr  "tggggaggaatcagtcccactcaggacacagcatggacatgagggtccccgctcagctcctggggctcctgctgctctggttcccaggtgccaggtgtgacatccagatga"| __truncated__ "tggggaggaatcagtcccactcaggacacagcatggacatgagggtccccgctcagctcctggggctcctgctgctctggttcccaggtgccaggtgtgacatccagatga"| __truncated__ "gagctctgggagaggagcccagcactagaggtcggcggtgtttccattcggtgatcagcactgaacacagaggactcaccatggagtttgggctgagctgggttttcctcg"| __truncated__ "gaagagctgctcagttaggacccagagggaaccatggaaaccccagcgcagcttctcttcctcctgctactctggctcccagatatcaccggagaagttgtattgacgcag"| __truncated__ ...
 $ subject               : chr  "S144" "S144" "S144" "S12282" ...
 $ status                : chr  "singlet" "singlet" "singlet" "singlet" ...
 $ isSinglet             : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ isDoublet             : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ molecule              : chr  "nt" "nt" "nt" "nt" ...
 $ receptor              : chr  "BCR" "BCR" "BCR" "BCR" ...
 $ v_geneIMGT            : chr  "1-17" "1-17" "3-30" "3-20" ...
 $ isMedSeqLen           : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ distDomCDR3           : num  0 0 0 0 0 0 1 0 0 2 ...
 $ distDomSeq            : num  3 1 4 0 0 1 8 2 2 3 ...
 $ domVgeneCR            : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ domVgeneIMGT          : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ clone                 : num  NA NA NA 1 1 5 227 198 5 NA ...
 $ count                 : int  NA NA NA 262 62 72 1 1 85 NA ...
 $ distVgene             : num  NA NA NA 19 24 9 27 10 22 NA ...
 $ distJgene             : num  NA NA NA 3 16 2 10 2 10 NA ...
 $ distPO                : num  NA NA NA 15 29 5 25 6 21 NA ...
 - attr(*, ".internal.selfref")=<externalptr>

In [13]:
options(repr.matrix.max.cols = 150)
head(clone_id)

  source cell             Sequence ID                 V-DOMAIN Functionality
1 K1B    AACTCAGCATTCGACA AACTCAGCATTCGACA-1_contig_1 productive
2 K1B    AACTCAGCATTCGACA AACTCAGCATTCGACA-1_contig_2 productive
3 K1B    AACTCAGCATTCGACA AACTCAGCATTCGACA-1_contig_3 productive
4 K1B    AACTCTTGTGCAACTT AACTCTTGTGCAACTT-1_contig_1 productive
5 K1B    AACTCTTGTGCAACTT AACTCTTGTGCAACTT-1_contig_2 productive
6 K1B    ACACCCTCACACCGCA ACACCCTCACACCGCA-1_contig_1 productive
  V-GENE and allele                                  J-GENE and allele
1 IGKV1-17*01 F                                      IGKJ4*01 F
2 IGKV1-17*01 F                                      IGKJ4*01 F
3 IGHV3-30*03 F, or IGHV3-30*18 F or IGHV3-30-5*01 F IGHJ6*02 F
4 IGKV3-20*01 F                                      IGKJ2*01 F
5 IGHV3-11*05 F                                      IGHJ3*01 F
6 IGKV1-17*01 F                                      IGKJ4*01 F
  D-GENE and allele
1 NA
2 NA
3 IGHD3-10*01 F
4 NA
5 IGHD2-21*02 F
6 NA
  V-REGION
1 gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccttcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttacttctgtctacagcataatacttaccc
2 gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgtctacagcataatacttaccc
3 caggagcaactggtggagtctgggggaggcgtgatccagcctgggaggtccctgagactctcctgtgcagcctctcgatttatcttcagtaactttggcatgcactgggtccgccaggcaccaggcaaggggctggagtgggtggcaaatatatcatatgatggaactaataaatactatggcgacttcgtgaagggccgattcaccatctccagagacaattccaagaacacggtgtatttgcaaatgaacagcctgagacctgatgacacggctgtatatttctgtgcgag
4 gaagttgtattgacgcagtctccaggcaccctgtctctgtctccagggcaaagagccaccctctcctgcagggccagtcagagtattagtagcagctacttagcctggtaccagcagaaacctggccaggctcccaggctcctcatttatggtgcatccagcaaggccactggcatcccagacaggttcactggcaacgggtctgggacagacttcactctcaacatcggcagactggagactgaagattttgcagtgtattactgtcaacagtatggtaggtctcc
5 ctagtgcagctggtggagtctgggggaggcttggtcaagcctggagggtccctgagactctcctgtgcagcctctggatttaccttcagtgactattatatgaattggattcgccaggcgccagggaaggggctggagtgggtttcaaatattagtagtacaaatacttatacaaactatgcagactctgtgaagggccgattcatcatttccagagacaacgccaagaactcactgtttctgcaaatgaacagcctgagagtcgaggacacggccgtgtacttctgtgcgagag
6 gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgtctacagcataatacttaccc
  FR3-IMGT
1 agtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttacttctgt
2 agtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgt
3 tactatggcgacttcgtgaagggccgattcaccatctccagagacaattccaagaacacggtgtatttgcaaatgaacagcctgagacctgatgacacggctgtatatttctgt
4 agcaaggccactggcatcccagacaggttcactggcaacgggtctgggacagacttcactctcaacatcggcagactggagactgaagattttgcagtgtattactgt
5 aactatgcagactctgtgaagggccgattcatcatttccagagacaacgccaagaactcactgtttctgcaaatgaacagcctgagagtcgaggacacggccgtgtacttctgt
6 agtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgt
  FR4-IMGT
1 ttcggcggagggaccaaggtggagatcaaac
2 ttcggcggagggaccaaggtggagatcaaac
3 tggggccaagggaccacggtcaccgtctcgtca
4 tttggccaggggaccaaggtggagatcaaag
5 tggggccgggggaccacggtcaccgtcttctcag
6 ttcggcggagggaccaaggtggagatcaaac
  JUNCTION
1 tgtctacagcataatacttacccactcgctttc
2 tgtctacagcataatacttacccactcgctttc
3 tgtgcgagggggcgtggggcgttcgcagtgatgcgaggcggcgactacaacggtatggacgtctgg
4 tgtcaacagtatggtaggtctccgtacactttt
5 tgtgcgagaggggaaggggtggctgcacttcccaatgctatggacgtctgg
6 tgtctacagcataatacttacccactcgctttc
  Vregion3Prime           FR1-IMGT start FR3-IMGT end FR4-IMGT start
1 tgtctacagcataatacttaccc  99            362          390
2 tgtctacagcataatacttaccc  99            362          390
3 tgtgcgag                138            425          486
4 tgtcaacagtatggtaggtctcc  94            360          388
5 tgtgcgagag              138            425          471
6 tgtctacagcataatacttaccc 101            364          392
  J-REGION
1 ctcgctttcggcggagggaccaaggtggagatcaaac
2 ctcgctttcggcggagggaccaaggtggagatcaaac
3 actacaacggtatggacgtctggggccaagggaccacggtcaccgtctcgtca
4 gtacacttttggccaggggaccaaggtggagatcaaag
5 gacgtctggggccgggggaccacggtcaccgtcttctcag
6 ctcgctttcggcggagggaccaaggtggagatcaaac
  CDR3-IMGT                                                    FR4-IMGT end
1 ctacagcataatacttacccactcgct                                  420
2 ctacagcataatacttacccactcgct                                  420
3 gcgagggggcgtggggcgttcgcagtgatgcgaggcggcgactacaacggtatggacgtc 518
4 caacagtatggtaggtctccgtacact                                  418
5 gcgagaggggaaggggtggctgcacttcccaatgctatggacgtc                504
6 ctacagcataatacttacccactcgct                                  422
  seq
1 gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccttcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttacttctgtctacagcataatacttacccactcgctttcggcggagggaccaaggtggagatcaaac
2 gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgtctacagcataatacttacccactcgctttcggcggagggaccaaggtggagatcaaac
3 caggagcaactggtggagtctgggggaggcgtgatccagcctgggaggtccctgagactctcctgtgcagcctctcgatttatcttcagtaactttggcatgcactgggtccgccaggcaccaggcaaggggctggagtgggtggcaaatatatcatatgatggaactaataaatactatggcgacttcgtgaagggccgattcaccatctccagagacaattccaagaacacggtgtatttgcaaatgaacagcctgagacctgatgacacggctgtatatttctgtgcgagggggcgtggggcgttcgcagtgatgcgaggcggcgactacaacggtatggacgtctggggccaagggaccacggtcaccgtctcgtca
4 gaagttgtattgacgcagtctccaggcaccctgtctctgtctccagggcaaagagccaccctctcctgcagggccagtcagagtattagtagcagctacttagcctggtaccagcagaaacctggccaggctcccaggctcctcatttatggtgcatccagcaaggccactggcatcccagacaggttcactggcaacgggtctgggacagacttcactctcaacatcggcagactggagactgaagattttgcagtgtattactgtcaacagtatggtaggtctccgtacacttttggccaggggaccaaggtggagatcaaag
5 ctagtgcagctggtggagtctgggggaggcttggtcaagcctggagggtccctgagactctcctgtgcagcctctggatttaccttcagtgactattatatgaattggattcgccaggcgccagggaaggggctggagtgggtttcaaatattagtagtacaaatacttatacaaactatgcagactctgtgaagggccgattcatcatttccagagacaacgccaagaactcactgtttctgcaaatgaacagcctgagagtcgaggacacggccgtgtacttctgtgcgagaggggaaggggtggctgcacttcccaatgctatggacgtctggggccgggggaccacggtcaccgtcttctcag
6 gacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgtctacagcataatacttacccactcgctttcggcggagggaccaaggtggagatcaaac
  gene genes contigCount barcode            is_cell high_confidence length
1 K    NA    1           AACTCAGCATTCGACA-1 FALSE   FALSE           556
2 K    NA    1           AACTCAGCATTCGACA-1 FALSE   FALSE           556
3 H    NA    1           AACTCAGCATTCGACA-1 FALSE   FALSE           590
4 K    HK    1           AACTCTTGTGCAACTT-1  TRUE    TRUE           554
5 H    HK    1           AACTCTTGTGCAACTT-1  TRUE    TRUE           575
6 K    HK    1           ACACCCTCACACCGCA-1  TRUE    TRUE           558
  chain v_gene   d_gene j_gene c_gene full_length productive
1 IGK   IGKV1-17 None   IGKJ4  IGKC   TRUE        TRUE
2 IGK   IGKV1-17 None   IGKJ4  IGKC   TRUE        TRUE
3 IGH   IGHV3-30 None   IGHJ6  IGHM   TRUE        TRUE
4 IGK   IGKV3-20 None   IGKJ2  IGKC   TRUE        TRUE
5 IGH   IGHV3-11 None   IGHJ6  IGHM   TRUE        TRUE
6 IGK   IGKV1-17 None   IGKJ4  IGKC   TRUE        TRUE
  cdr3                   reads umis V-REGION identity %
1 CLQHNTYPLAF             3644 17   97.13
2 CLQHNTYPLAF             3140 15   97.85
3 CARGRGAFAVMRGGDYNGMDVW  1580  9   92.71
4 CQQYGRSPYTF             7664 43   94.33
5 CARGEGVAALPNAMDVW        718  3   92.01
6 CLQHNTYPLAF            10288 49   97.85
  seqRaw
1 tggggaggaatcagtcccactcaggacacagcatggacatgagggtccccgctcagctcctggggctcctgctgctctggttcccaggtgccaggtgtgacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccttcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttacttctgtctacagcataatacttacccactcgctttcggcggagggaccaaggtggagatcaaacgaactgtggctgcaccatctgtcttcatcttcccgccatctgatgagcagttgaaatctggaactgcctctgttgtgtgcctgctgaataacttctatcccagagaggccaaagtacagtggaaggtggataacgc
2 tggggaggaatcagtcccactcaggacacagcatggacatgagggtccccgctcagctcctggggctcctgctgctctggttcccaggtgccaggtgtgacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgtctacagcataatacttacccactcgctttcggcggagggaccaaggtggagatcaaacgaactgtggctgcaccatctgtcttcatcttcccgccatctgatgagcagttgaaatctggaactgcctctgttgtgtgcctgctgaataacttctatcccagagaggccaaagtacagtggaaggtggataacgc
3 gagctctgggagaggagcccagcactagaggtcggcggtgtttccattcggtgatcagcactgaacacagaggactcaccatggagtttgggctgagctgggttttcctcgttgctcttttaagaggtgtccagtgtcaggagcaactggtggagtctgggggaggcgtgatccagcctgggaggtccctgagactctcctgtgcagcctctcgatttatcttcagtaactttggcatgcactgggtccgccaggcaccaggcaaggggctggagtgggtggcaaatatatcatatgatggaactaataaatactatggcgacttcgtgaagggccgattcaccatctccagagacaattccaagaacacggtgtatttgcaaatgaacagcctgagacctgatgacacggctgtatatttctgtgcgagggggcgtggggcgttcgcagtgatgcgaggcggcgactacaacggtatggacgtctggggccaagggaccacggtcaccgtctcgtcagggagtgcatccgccccaacccttttccccctcgtctcctgtgagaattccccgtcggatacgagcagcgtg
4 gaagagctgctcagttaggacccagagggaaccatggaaaccccagcgcagcttctcttcctcctgctactctggctcccagatatcaccggagaagttgtattgacgcagtctccaggcaccctgtctctgtctccagggcaaagagccaccctctcctgcagggccagtcagagtattagtagcagctacttagcctggtaccagcagaaacctggccaggctcccaggctcctcatttatggtgcatccagcaaggccactggcatcccagacaggttcactggcaacgggtctgggacagacttcactctcaacatcggcagactggagactgaagattttgcagtgtattactgtcaacagtatggtaggtctccgtacacttttggccaggggaccaaggtggagatcaaaggaactgtggctgcaccatctgtcttcatcttcccgccatctgatgagcagttgaaatctggaactgcctctgttgtgtgcctgctgaataacttctatcccagagaggccaaagtacagtggaaggtggataacgc
5 agctctgggagaagagccccagccccagaactcccaggagtttccattcggtgatcagcactgaacacagaggactcaccatggagtttgggctgagctgggttttccttgttgctattataaaaggtgtccagtgtctagtgcagctggtggagtctgggggaggcttggtcaagcctggagggtccctgagactctcctgtgcagcctctggatttaccttcagtgactattatatgaattggattcgccaggcgccagggaaggggctggagtgggtttcaaatattagtagtacaaatacttatacaaactatgcagactctgtgaagggccgattcatcatttccagagacaacgccaagaactcactgtttctgcaaatgaacagcctgagagtcgaggacacggccgtgtacttctgtgcgagaggggaaggggtggctgcacttcccaatgctatggacgtctggggccgggggaccacggtcaccgtcttctcagggagtgcatccgccccaacccttttccccctcgtctcctgtgagaattccccgtcggatacgagcagcgtg
6 catggggaggaatcagtcccactcaggacacagcatggacatgagggtccccgctcagctcctggggctcctgctgctctggttcccaggtgccaggtgtgacatccagatgacccagtctccatcctccctgtctgcatctgtaggagacagagtcaccatcacttgccgggcaagtcagggcattagaaatgatttaggctggtttcagcagaaaccagggaaagcccctaagcgcctgatctatgctgcatccagtttgcaaagtggggtcccatcaaggttcagcggctatggatctgggacagagttcactctcacaatcagcagcctgcagcctgaagattttgcaacttatttctgtctacagcataatacttacccactcgctttcggcggagggaccaaggtggagatcaaacgaactgtggctgcaccatctgtcttcatcttcccgccatctgatgagcagttgaaatctggaactgcctctgttgtgtgcctgctgaataacttctatcccagagaggccaaagtacagtggaaggtggataacgc
  subject status  isSinglet isDoublet molecule receptor v_geneIMGT isMedSeqLen
1 S144    singlet TRUE      FALSE     nt       BCR      1-17       TRUE
2 S144    singlet TRUE      FALSE     nt       BCR      1-17       TRUE
3 S144    singlet TRUE      FALSE     nt       BCR      3-30       TRUE
4 S12282  singlet TRUE      FALSE     nt       BCR      3-20       TRUE
5 S12282  singlet TRUE      FALSE     nt       BCR      3-11       TRUE
6 S144    singlet TRUE      FALSE     nt       BCR      1-17       TRUE
  distDomCDR3 distDomSeq domVgeneCR domVgeneIMGT clone count distVgene
1 0           3          TRUE       TRUE         NA     NA   NA
2 0           1          TRUE       TRUE         NA     NA   NA
3 0           4          TRUE       TRUE         NA     NA   NA
4 0           0          TRUE       TRUE          1    262   19
5 0           0          TRUE       TRUE          1     62   24
6 0           1          TRUE       TRUE          5     72    9
  distJgene distPO
1 NA        NA
2 NA        NA
3 NA        NA
4  3        15
5 16        29
6  2         5

In [14]:
clone_id %>% pull(source) %>% unique()

[1] "K1B" "K2B" "K3B"

In [8]:
clone_id %>% select(cell,chain,"Sequence ID",is_cell,productive, isDoublet,clone) %>% group_by(cell,chain,clone) %>% count() %>%
left_join(df_summary, "cell")

    cell             chain clone n subject       vgene_position_aligned nucl_po
1   AAATGCCTCTGAAAGA IGH    NA   3 K2B_S13530-LC  10                    C
2   AAATGCCTCTGAAAGA IGL    NA   1 K2B_S13530-LC  10                    C
3   AAATGCCTCTGAAAGA Multi  NA   2 K2B_S13530-LC  10                    C
4   AACACGTAGCCACCTG IGK    13   1 K2B_S13553-LC 165                    C
5   AACTCAGCAAATCCGT IGH    13   1 K2B_S13530-HC   1                    G
6   AACTCAGCAAATCCGT IGH    13   1 K2B_S13530-HC  13                    G
7   AACTCAGCAAATCCGT Multi   1   1 K2B_S13530-HC   1                    G
8   AACTCAGCAAATCCGT Multi   1   1 K2B_S13530-HC  13                    G
9   AACTCAGCAAATCCGT Multi   2   1 K2B_S13530-HC   1                    G
10  AACTCAGCAAATCCGT Multi   2   1 K2B_S13530-HC  13                    G
11  AACTCAGCATTCGACA IGH    NA   1 K1B_S144-LC    61                    A
12  AACTCAGCATTCGACA IGK    NA   2 K1B_S144-LC    61                    A
13  AACTCCCAGATATACG IGH     1   1 K2B_S13530-HC  71                    C
14  AACTCCCAGATATACG Multi  31   1 K2B_S13530-HC  71                    C
15  AACTCCCAGATATACG Multi 176   1 K2B_S13530-HC  71                    C
16  AACTCCCAGCGATATA IGH     1   1 K2B_S13553-LC 132                    G
17  AACTCCCAGCGATATA IGK     1   1 K2B_S13553-LC 132                    G
18  AACTCTTGTGCAACTT IGH     1   1 K1B_S12282-LC   9                    G
19  AACTCTTGTGCAACTT IGH     1   1 K1B_S12282-LC  89                    G
20  AACTCTTGTGCAACTT IGK     1   1 K1B_S12282-LC   9                    G
21  AACTCTTGTGCAACTT IGK     1   1 K1B_S12282-LC  89                    G
22  ACACCCTCACACCGCA IGH   227   1 K1B_S144-LC    46                    G
23  ACACCCTCACACCGCA IGK     5   1 K1B_S144-LC    46                    G
24  ACGCAGCAGCAGGCTA IGH     5   1 K1B_S144-LC    54                    A
25  ACGCAGCAGCAGGCTA IGK   198   1 K1B_S144-LC    54                    A
26  ACGCCAGAGGCATTGG IGH    NA   1 K1B_S144-LC    25                    T
27  ACGCCAGAGGCATTGG IGH    NA   1 K1B_S144-LC    94                    G
28  ACGCCAGAGGCATTGG IGK    NA   2 K1B_S144-LC    25                    T
29  ACGCCAGAGGCATTGG IGK    NA   2 K1B_S144-LC    94                    G
30  ACGCCAGAGGCATTGG IGL    NA   1 K1B_S144-LC    25                    T
⋮   ⋮                ⋮     ⋮     ⋮ ⋮             ⋮                      ⋮
210 TGCTGCTGTACAGTGG IGK    64   1 K1B_S144-LC   122                    G
211 TGCTGCTGTACAGTGG IGK    82   1 K1B_S144-LC    47                    G
212 TGCTGCTGTACAGTGG IGK    82   1 K1B_S144-LC   122                    G
213 TGGCTGGGTAGTAGTA IGH    NA   2 K2B_S13530-HC 155                    G
214 TGGCTGGGTAGTAGTA IGL    NA   1 K2B_S13530-HC 155                    G
215 TGGCTGGGTAGTAGTA Multi  NA   2 K2B_S13530-HC 155                    G
216 TGTGGTAAGGCGACAT IGH     5   1 K1B_S144-LC    39                    A
217 TGTGGTAAGGCGACAT IGH     5   1 K1B_S144-LC    45                    A
218 TGTGGTAAGGCGACAT IGH     5   1 K1B_S144-LC   134                    A
219 TGTGGTAAGGCGACAT IGK   208   1 K1B_S144-LC    39                    A
220 TGTGGTAAGGCGACAT IGK   208   1 K1B_S144-LC    45                    A
221 TGTGGTAAGGCGACAT IGK   208   1 K1B_S144-LC   134                    A
222 TGTTCCGTCGGCGCAT IGH     1   1 K2B_S13553-LC 153                    G
223 TGTTCCGTCGGCGCAT IGK    16   1 K2B_S13553-LC 153                    G
224 TTAGGCAGTCGAACAG IGH     6   1 K1B_S10000-LC  10                    C
225 TTAGGCAGTCGAACAG IGL    16   1 K1B_S10000-LC  10                    C
226 TTATGCTCACACCGAC IGH     5   1 K1B_S144-LC    95                    A
227 TTATGCTCACACCGAC IGK     7   1 K1B_S144-LC    95                    A
228 TTATGCTCATCCTTGC IGH    NA   1 K1B_S144-LC    73                    G
229 TTATGCTCATCCTTGC IGH    NA   1 K1B_S144-LC   106                    T
230 TTATGCTCATCCTTGC IGK    NA   2 K1B_S144-LC    73                    G
231 TTATGCTCATCCTTGC IGK    NA   2 K1B_S144-LC   106                    T
232 TTATGCTCATCCTTGC IGL    NA   1 K1B_S144-LC    73                    G
233 TTATGCTCATCCTTGC IGL    NA   1 K1B_S144-LC   106                    T
234 TTTCCTCCACTTAAGC IGH   118   1 K1B_S144-LC     4                    A
235 TTTCCTCCACTTAAGC IGH   118   1 K1B_S144-LC     8                    A
236 TTTCCTCCACTTAAGC IGH   118   1 K1B_S144-LC    10                    A
237 TTTCCTCCACTTAAGC IGK   151   1 K1B_S144-LC     4                    A
238 TTTCCTCCACTTAAGC IGK   151   1 K1B_S144-LC     8                    A
239 TTTCCTCCACTTAAGC IGK   151   1 K1B_S144-LC    10                    A
    context_po subregion variation umis  productive
1   AG.TG      FR1       C-T       16-22 TRUE
2   AG.TG      FR1       C-T       16-22 TRUE
3   AG.TG      FR1       C-T       16-22 TRUE
4   TA.TG      FR2       C-T       5-5   TRUE
5   .AG        FR1       A-G       9-13  TRUE
6   TG.TG      FR1       A-G       10-9  TRUE
7   .AG        FR1       A-G       9-13  TRUE
8   TG.TG      FR1       A-G       10-9  TRUE
9   .AG        FR1       A-G       9-13  TRUE
10  TG.TG      FR1       A-G       10-9  TRUE
11  CC.TC      FR1       A-T       8-13  TRUE
12  CC.TC      FR1       A-T       8-13  TRUE
13  AG.CT      FR1       C-G       5-6   TRUE
14  AG.CT      FR1       C-G       5-6   TRUE
15  AG.CT      FR1       C-G       5-6   TRUE
16  CA.AA      FR2       C-G       5-8   TRUE
17  CA.AA      FR2       C-G       5-8   TRUE
18  GT.TT      FR1       A-C       14-9  TRUE
19  TA.CA      CDR1      C-G       7-11  TRUE
20  GT.TT      FR1       A-C       14-9  TRUE
21  TA.CA      CDR1      C-G       7-11  TRUE
22  TA.GA      FR1       A-G       19-20 TRUE
23  TA.GA      FR1       A-G       19-20 TRUE
24  AG.GT      FR1       A-C       9-11  TRUE
25  AG.GT      FR1       A-C       9-11  TRUE
26  CA.CC      FR1       C-T       13-13 TRUE
27  AT.AT      CDR1      C-G       12-12 TRUE
28  CA.CC      FR1       C-T       13-13 TRUE
29  AT.AT      CDR1      C-G       12-12 TRUE
30  CA.CC      FR1       C-T       13-13 TRUE
⋮   ⋮          ⋮         ⋮         ⋮     ⋮
210 AG.GA      FR2       A-G       14-18 TRUE
211 AG.AG      FR1       A-G       23-16 TRUE
212 AG.GA      FR2       A-G       14-18 TRUE
213 TA.TA      CDR2      C-G       8-5   TRUE
214 TA.TA      CDR2      C-G       8-5   TRUE
215 TA.TA      CDR2      C-G       8-5   TRUE
216 GC.TC      FR1       A-T       11-15 TRUE
217 GT.GG      FR1       A-C       15-11 TRUE
218 TA.GC      FR2       A-G       7-11  TRUE
219 GC.TC      FR1       A-T       11-15 TRUE
220 GT.GG      FR1       A-C       15-11 TRUE
221 TA.GC      FR2       A-G       7-11  TRUE
222 AA.CT      FR2       A-G       12-9  TRUE
223 AA.CT      FR2       A-G       12-9  TRUE
224 TG.TG      FR1       C-T       5-8   TRUE
225 TG.TG      FR1       C-T       5-8   TRUE
226 TG.TT      CDR1      A-C       9-5   TRUE
227 TG.TT      CDR1      A-C       9-5   TRUE
228 GG.CA      FR1       G-T       22-32 TRUE
229 GG.AT      FR2       A-T       22-30 TRUE
230 GG.CA      FR1       G-T       22-32 TRUE
231 GG.AT      FR2       A-T       22-30 TRUE
232 GG.CA      FR1       G-T       22-32 TRUE
233 GG.AT      FR2       A-T       22-30 TRUE
234 AC.TC      FR1       A-G       6-7   TRUE
235 CC.GA      FR1       A-G       6-7   TRUE
236 AG.TG      FR1       A-G       6-7   TRUE
237 AC.TC      FR1       A-G       6-7   TRUE
238 CC.GA      FR1       A-G       6-7   TRUE
239 AG.TG      FR1       A-G       6-7   TRUE

In [10]:
clone_id %>% select(cell,chain,"Sequence ID",is_cell,productive, isDoublet,clone) %>% filter(is_cell == FALSE ) %>% pull(cell) %>% unique() %>%
length()

[1] 14